-- ===========================================
-- Expense Tracker Database Tables
-- Created by Akshay - July 2025
-- ===========================================

-- 1 USERS Table
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    created_at DATE DEFAULT SYSDATE
);

-- 2 CATEGORIES Table
CREATE TABLE Categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_name VARCHAR2(100) NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) 
        REFERENCES Users(user_id) ON DELETE CASCADE
);

-- 3 EXPENSES Table
CREATE TABLE Expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    expense_date DATE NOT NULL,
    description VARCHAR2(200),
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) 
        REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_category FOREIGN KEY (category_id) 
        REFERENCES Categories(category_id) ON DELETE CASCADE
);
